### PR TITLE
Fix pooling #48

### LINKED ISSUE #48: Pooling of clusters is scoped per project
PoolingSubmitter looks at all clusters in a project, this should be segmented on a user provided value allowing multiple pools to coexist in a single project.

### PR DESCRIPTION
**Pull request by krisss85**
This PR is to fix #48 
PoolingSubmitter looks at all clusters in a project, this should be segmented on a user provided value allowing multiple pools to coexist in a single project.

### CODE REVIEW

File: spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java [hunk 1]
```diff
@@ -155,6 +157,9 @@ boolean createNewCluster(SpydraArgument arguments, DataprocAPI dataprocAPI)
     } else {
       createArguments = arguments;
     }
+
+    arguments.addOption(createArguments.cluster.options, SpydraArgument.OPTION_LABELS, SPYDRA_CLUSTER_LABEL + "=1");
```
Comment (Xeago) [inline spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java]: What is the semantic meaning of 1 here?

Comment (krisss85) [reply spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java]: Just to mark it as a spydra cluster, so to take it into consideration.

File: spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java [hunk 2]
```diff
@@ -97,21 +102,34 @@ public boolean acquireCluster(SpydraArgument arguments, DataprocAPI dataprocAPI)
...
-        .filter(cluster -> cluster.clusterName.equals(arguments.getCluster().getName()))
-        .findAny().map(cluster -> cluster.status.state.equals(Cluster.Status.ERROR)).orElse(false);
-
+    Map<String, String> clusterFilter = ImmutableMap.of(
+            "status.state", "ERROR",
+            OPTIONS_FILTER_LABEL_PREFIX + SPYDRA_CLUSTER_LABEL, "",
+            OPTIONS_FILTER_LABEL_PREFIX + POOLED_CLUSTER_CLIENTID_LABEL, arguments.getClientId()
+    );
+    shouldCollect = shouldCollect || dataprocAPI.listClusters(arguments, clusterFilter).stream()
+            .filter(cluster -> cluster.clusterName.equals(arguments.getCluster().getName()))
```
Comment (Xeago) [inline spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java]: Instead of this filter, use `clusterName` in the clusterFilter.

File: spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java (hunk 1 above)
Comment (Xeago) [reply spydra/src/main/java/com/spotify/spydra/submitter/api/DynamicSubmitter.java]: Ok.

File: spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java (hunk 2 above)
Comment (krisss85) [reply spydra/src/main/java/com/spotify/spydra/submitter/api/PoolingSubmitter.java]: Sth like this?
``` "cluster.clusterName", arguments.getCluster().getName(), ```

File: api/src/main/java/com/spotify/spydra/api/DataprocAPI.java [hunk 3]
```diff
@@ -113,7 +114,7 @@ public boolean updateMasterMetadata(SpydraArgument arguments, String key, String
     return success;
   }
 
-  public Collection<Cluster> listClusters(SpydraArgument arguments) throws IOException {
-    return gcloud.listClusters(arguments.cluster.getOptions().get("project"), arguments.getRegion());
+  public Collection<Cluster> listClusters(SpydraArgument arguments, Map<String, String> filters) throws IOException {
```
Comment (Xeago) [inline api/src/main/java/com/spotify/spydra/api/DataprocAPI.java]: I wonder how much of the underlying `gcloud` implementation for `dataproc` we are leaking through here. Not something I worry about overly much though.
